name: "demo for cron"
on: 
    schedule:
      - cron: "*/5 * * * *"
jobs:
  demo-cron:
    runs-on: ubuntu-latest
    steps:
      - name: print the message
        run: echo "cron it will depends on time"